import { type User } from '../users/user-types'

export const users: User[] = [
  {
    id: 1,
    name: 'Emily Johnson',
    email: 'emily.johnson@x.dummyjson.com',
    image: 'https://dummyjson.com/icon/emilys/128',
    phone: '+81 965-431-3024',
  },
  {
    id: 2,
    name: 'Michael Williams',
    email: 'michael.williams@x.dummyjson.com',
    image: 'https://dummyjson.com/icon/michaelw/128',
    phone: '+49 258-627-6644',
  },
  {
    id: 3,
    name: 'Sophia Brown',
    email: 'sophia.brown@x.dummyjson.com',
    phone: '+81 210-652-2785',
  },
  {
    id: 4,
    name: 'James Davis',
    email: 'james.davis@x.dummyjson.com',
    image: 'https://dummyjson.com/icon/jamesd/128',
    phone: '+49 614-958-9364',
  },
  {
    id: 5,
    name: 'Olivia Wilson',
    email: 'olivia.wilson@x.dummyjson.com',
    image: 'https://dummyjson.com/icon/oliviaw/128',
    phone: '+1 305-558-7895',
  },
  {
    id: 6,
    name: 'Liam Martinez',
    email: 'liam.martinez@x.dummyjson.com',
    image: 'https://dummyjson.com/icon/liamm/128',
    phone: '+44 732-490-1238',
  },
  {
    id: 7,
    name: 'Isabella Garcia',
    email: 'isabella.garcia@x.dummyjson.com',
    image: 'https://dummyjson.com/icon/isabellag/128',
    phone: '+33 613-740-9821',
  },
  {
    id: 8,
    name: 'Benjamin Miller',
    email: 'benjamin.miller@x.dummyjson.com',
    image: 'https://dummyjson.com/icon/benjaminm/128',
    phone: '+81 564-728-4052',
  },
  {
    id: 9,
    name: 'Mia Rodriguez',
    email: 'mia.rodriguez@x.dummyjson.com',
    image: 'https://dummyjson.com/icon/miar/128',
    phone: '+49 152-486-3778',
  },
  {
    id: 10,
    name: 'Noah Anderson',
    email: 'noah.anderson@x.dummyjson.com',
    image: 'https://dummyjson.com/icon/noaha/128',
    phone: '+1 204-962-7512',
  },
  {
    id: 11,
    name: 'Emma Taylor',
    email: 'emma.taylor@x.dummyjson.com',
    image: 'https://dummyjson.com/icon/emmat/128',
    phone: '+44 915-503-1289',
  },
  {
    id: 12,
    name: 'Lucas Thomas',
    email: 'lucas.thomas@x.dummyjson.com',
    image: 'https://dummyjson.com/icon/lucast/128',
    phone: '+33 735-892-4263',
  },
  {
    id: 13,
    name: 'Charlotte Moore',
    email: 'charlotte.moore@x.dummyjson.com',
    image: 'https://dummyjson.com/icon/charlottem/128',
    phone: '+49 613-827-3106',
  },
  {
    id: 14,
    name: 'Elijah Jackson',
    email: 'elijah.jackson@x.dummyjson.com',
    image: 'https://dummyjson.com/icon/elijahj/128',
    phone: '+81 310-621-9054',
  },
  {
    id: 15,
    name: 'Amelia White',
    email: 'amelia.white@x.dummyjson.com',
    image: 'https://dummyjson.com/icon/ameliaw/128',
    phone: '+44 812-467-1943',
  },
  {
    id: 16,
    name: 'William Harris',
    email: 'william.harris@x.dummyjson.com',
    image: 'https://dummyjson.com/icon/williamh/128',
    phone: '+1 714-325-5907',
  },
  {
    id: 17,
    name: 'Ava Clark',
    email: 'ava.clark@x.dummyjson.com',
    image: 'https://dummyjson.com/icon/avac/128',
    phone: '+33 726-815-4871',
  },
  {
    id: 18,
    name: 'Ethan Lewis',
    email: 'ethan.lewis@x.dummyjson.com',
    image: 'https://dummyjson.com/icon/ethanl/128',
    phone: '+49 512-498-7623',
  },
  {
    id: 19,
    name: 'Harper Young',
    email: 'harper.young@x.dummyjson.com',
    image: 'https://dummyjson.com/icon/harpery/128',
    phone: '+81 984-721-6451',
  },
  {
    id: 20,
    name: 'Alexander King',
    email: 'alexander.king@x.dummyjson.com',
    image: 'https://dummyjson.com/icon/alexanderk/128',
    phone: '+1 302-781-9345',
  },
  {
    id: 21,
    name: 'Ella Wright',
    email: 'ella.wright@x.dummyjson.com',
    image: 'https://dummyjson.com/icon/ellaw/128',
    phone: '+44 782-564-9103',
  },
  {
    id: 22,
    name: 'Henry Walker',
    email: 'henry.walker@x.dummyjson.com',
    image: 'https://dummyjson.com/icon/henryw/128',
    phone: '+33 614-923-5724',
  },
  {
    id: 23,
    name: 'Abigail Hall',
    email: 'abigail.hall@x.dummyjson.com',
    image: 'https://dummyjson.com/icon/abigailh/128',
    phone: '+49 502-398-7102',
  },
  {
    id: 24,
    name: 'Daniel Adams',
    email: 'daniel.adams@x.dummyjson.com',
    image: 'https://dummyjson.com/icon/daniela/128',
    phone: '+81 874-362-9185',
  },
]
